### ISSUE TITLE
Increase arm speed

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/Robot2023#262]
Let's bump it up until it scares us.

**Comment by IanSzalai** [comment]
this needs to be achieved with some form of trapezoidal motion. I really would like to use trapezoidal motion on the intake position and leave the joints unconstrained, but this would take some time. in case this isn't possible, we can use [CTRE Motion Magic ](https://v5.docs.ctr-electronics.com/en/stable/ch16_ClosedLoop.html#motion-magic-position-velocity-current-closed-loop-closed-loop)

the reason we need to use trapezoidal motion for this is because of the mechanical flex in the arm. if the deceleration is too great, the arm will bounce up and down before coming to a stop, meaning that just moving the arm slower will end up being a faster way to get the arm in position.
